Repository ZiaCodes/claim-prize, pull requests merged in 2022-02, with the labels that each got.

#9 Add email notification feature for new login
  Server/emails/welcome.js
  Server/example.env
  Server/package-lock.json
  Server/package.json
  Server/router/auth.js
Labels: good first issue, JWOC, Easy: 1 day, easy

#10 fixed session bug in signin route
  Server/router/auth.js
Labels: JWOC, Easy: 1 day, easy

#22 Designed a register page
  client/package-lock.json
  client/src/assets/registration_img.png
  client/src/components/register.jsx
  client/src/styles/register.css
Labels: JWOC, Easy: 1 day, easy

#21 🚀 feat: Added Landing Page
  client/src/assets/home-superhero.svg
  client/src/components/nav.jsx
  client/src/container/Home.jsx
Labels: JWOC, Easy: 1 day, easy

#28 Updated home page in ReactJS
  client/src/assets/Ellipse.png
  client/src/assets/SemiEllipse.png
  client/src/assets/landing-page.png
  client/src/container/Home.jsx
  client/src/styles/home.css
Labels: JWOC, Medium: 2-3 days, medium

#27 fixed the code causing deployment failure in vercel
  client/src/components/about.jsx
  client/src/components/register.jsx
  client/src/container/Home.jsx
Labels: JWOC, Medium: 2-3 days, medium

#29 connected frontend to backend
  Server/.gitignore
  Server/emails/welcome.js
  Server/key.env
  client/.env
  client/src/components/about.jsx
  client/src/components/login.jsx
  client/src/components/register.jsx
  client/src/services/AuthService.js
Labels: JWOC, Medium: 2-3 days, medium
